import type { GamesPageState } from "./types";

/**
 * Создаёт начальный снимок состояния страницы игр.
 */
export function createInitialGamesState(): GamesPageState {
  return {
    room: null,
    roomChatMessages: [],
    roomChatLoading: false,
    roomChatSending: false,
    roomChatError: "",
    roomChatDraft: "",
    roomChatShowSystemMessages: true,
    lobbyMode: "menu",
    rooms: [],
    roomsError: "",
    roomsSearchQuery: "",
    leaderboard: null,
    leaderboardLoading: false,
    leaderboardError: "",
    joinPasswordRoomId: "",
    joinInviteCodeValue: "",
    joinPasswordValue: "",
    joinPasswordVisible: false,
    joinInviteCodeError: "",
    joinPasswordError: "",
    disbandConfirmOpen: false,
    startConfirmOpen: false,
    leaveConfirmOpen: false,
    reportConfirmQuestionKey: "",
    questionMenuKey: "",
    profileNavigationConfirm: null,
    kickConfirmProfileId: "",
    adminConfirmProfileId: "",
    playerMenuProfileId: "",
    titleMenuOpen: false,
    passwordMenuOpen: false,
    passwordVisible: false,
    renameTitleModalOpen: false,
    passwordModalMode: "",
    floatingMenuAnchorX: 0,
    floatingMenuAnchorY: 0,
    participantsStatusHintOpen: false,
    readyStatusHintOpen: false,
    roomId: "",
    message: "",
    messageReturnRoomId: "",
    messageReturnInviteCode: "",
    messageReturnPassword: "",
    messageReturnRoomLabel: "",
    messageRefreshRooms: false,
    error: "",
    errorTarget: "",
    submittedQuestionId: "",
    submittedAnswerValue: "",
    socketOpen: false,
    loading: false,
    roomsLoading: false,
    roomsAutoRefreshEnabled: true,
  };
}
